import { z } from "zod";

export const MUSCLE_GROUPS = [
  "chest",
  "back",
  "shoulders",
  "biceps",
  "triceps",
  "forearms",
  "quadriceps",
  "hamstrings",
  "glutes",
  "calves",
  "core",
  "traps",
  "lats",
  "anterior_deltoids",
  "lateral_deltoids",
  "posterior_deltoids",
  "hip_flexors",
  "adductors",
  "abductors",
  "neck",
  "obliques",
  "lower_back",
  "upper_back",
] as const;

export const MuscleGroupSchema = z.enum(MUSCLE_GROUPS);
export type MuscleGroup = z.infer<typeof MuscleGroupSchema>;

export const MUSCLE_GROUP = {
  CHEST: "chest",
  BACK: "back",
  SHOULDERS: "shoulders",
  BICEPS: "biceps",
  TRICEPS: "triceps",
  FOREARMS: "forearms",
  QUADRICEPS: "quadriceps",
  HAMSTRINGS: "hamstrings",
  GLUTES: "glutes",
  CALVES: "calves",
  CORE: "core",
  TRAPS: "traps",
  LATS: "lats",
  ANTERIOR_DELTOIDS: "anterior_deltoids",
  LATERAL_DELTOIDS: "lateral_deltoids",
  POSTERIOR_DELTOIDS: "posterior_deltoids",
  HIP_FLEXORS: "hip_flexors",
  ADDUCTORS: "adductors",
  ABDUCTORS: "abductors",
  NECK: "neck",
  OBLIQUES: "obliques",
  LOWER_BACK: "lower_back",
  UPPER_BACK: "upper_back",
} as const satisfies Record<string, MuscleGroup>;

export const MUSCLE_GROUP_LABELS: Record<MuscleGroup, string> = {
  chest: "Chest",
  back: "Back",
  shoulders: "Shoulders",
  biceps: "Biceps",
  triceps: "Triceps",
  forearms: "Forearms",
  quadriceps: "Quadriceps",
  hamstrings: "Hamstrings",
  glutes: "Glutes",
  calves: "Calves",
  core: "Core",
  traps: "Traps",
  lats: "Lats",
  anterior_deltoids: "Anterior Deltoids",
  lateral_deltoids: "Lateral Deltoids",
  posterior_deltoids: "Posterior Deltoids",
  hip_flexors: "Hip Flexors",
  adductors: "Adductors",
  abductors: "Abductors",
  neck: "Neck",
  obliques: "Obliques",
  lower_back: "Lower Back",
  upper_back: "Upper Back",
};
